module.exports = [
    {
        name: "Hannah Abbott",
        role: "student",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Bathsheda Babbling",
        role: "Professor, Ancient Runes",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Ludo Bagman",
        role: "Head, Department of Magical Games and Sports",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Bathilda Bagshot",
        role: "Author, A History Of Magic",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Katie Bell",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Cuthbert Binns",
        role: "Professor, History of Magic",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Phineas Nigellus Black",
        role: "(Formerly) Headmaster of Hogwarts",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Regulus Black",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Sirius Black",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Amelia Bones",
        role: "Head, Department of Magical Law Enforcement",
        house: "Hufflepuff",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Susan Bones",
        role: "student",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Terry Boot",
        role: "student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Lavender Brown",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Millicent Bulstrode",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Frank Bryce",
        role: "Gardener, Riddle Family",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Charity Burbage",
        role: "Professor, Muggle Studies",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Alecto Carrow",
        role: "Professor, Muggle Studies",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Amycus Carrow",
        role: "Professor, Dark Arts",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Reginald Cattermole",
        role: "Employee, Magical Maintenance Department",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Mary Cattermole",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Cho Chang",
        role: "Student",
        house: "Ravenclaw",
        patronus: "swan",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Penelope Clearwater",
        role: "Student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Michael Corner",
        role: "Student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Crabbe",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Vincent Crabbe",
        role: "Student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Colin Creevey",
        role: "Student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Dennis Creevey",
        role: "Student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Dirk Cresswell",
        role: "Head, Goblin Liason Office",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Bartemius Crouch Sr.",
        role: "Head, Department of International Magical Cooperation",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Bartemius Crouch Jr.",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "John Dawlish",
        role: "Auror",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Fleur Delacour",
        role: "Student",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Gabrielle Delacour",
        role: "Student",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Dedalus Diggle",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Amos Diggory",
        role: "Employee, Department for the Regulation and Control of Magical Creatures",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Cedric Diggory",
        role: "Student",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Elphias Doge",
        role: "Special Advisor to the Wizengamot",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Antonin Dolohov",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,  
    },
    {
        name: "Aberforth Dumbledore",
        role: "Owner, Hog's Head Inn",
        house: "Gryffindor",       
        patronus: "goat",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Albus Dumbledore",
        role: "Headmaster, Hogwarts",
        house: "Gryffindor",
        patronus: "phoenix",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ariana Dumbledore",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Dudley Dursley",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Marjorie Dursley",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Petunia Dursley",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Vernon Dursley",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Marietta Edgecombe",
        role: "student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Everard",
        role: "(former) Headmaster, Hogwarts",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Arabella Figg",
        role: "Dealer of cross-bread cats and kneazies",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Argus Filch",
        role: "Caretaker, Hogwarts",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Justin Finch-Fletchley",
        role: "student",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Seamus Finnigan",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Marcus Flint",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Nicolas Flamel",
        role: "Alchemist",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Mundungus Fletcher",
        role: "Dealer of Wizarding Artifacts",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Filius Flitwick",
        role: "Professor, Charms",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Cornelius Fudge",
        role: "Minister of Magic",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Marvolo Gaunt",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Merope Gaunt",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Morfin Gaunt",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Anthony Goldstein",
        role: "student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Goyle Sr.",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Gregory Goyle",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Hermione Granger",
        role: "student",
        house: "Gryffindor",
        patronus: "otter",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Mykew Gregorovitch",
        role: "Wand Maker",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Fenrir Greyback",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,  
    },
    {
        name: "Gellert Grindelwald",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Wilhelmina Grubbly-Plank",
        role: "Professor, Care of Magical Creatures",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Godric Gryffindor",
        role: "Founder, Hogwarts",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Rubeus Hagrid",
        role: "Groundkeeper, Professor, Care of Magical Creatures",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Rolanda Hooch",
        role: "Quidditch Referee ",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Mafalda Hopkirk",
        role: "Assistant, mproper Use of Magic Office",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Helga Hufflepuff",
        role: "Founder, Hogwarts",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Angelina Johnson",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Lee Jordan",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Bertha Jorkins",
        role: "Department of Magical Games and Sports Employee",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Igor Karkaroff",
        role: "Headmaster, Durmstrang",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,  
    },
    {
        name: "Viktor Krum",
        role: "Bulgarian Quiddich Seeker",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Bellatrix Lestrange",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Rabastan Lestrange",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Rodolphus Lestrange",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Gilderoy Lockhart",
        role: "Professor, Defense Against the Dark Arts",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Alice Longbottom",
        role: "Auror (formerly)",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Frank Longbottom",
        role: "Auror (formerly)",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Augusta Longbottom",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Neville Longbottom",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Luna Lovegood",
        role: "student",
        house: "Ravenclaw",
        patronus: "hare",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false, 
    },
    {
        name: "Xenophilius Lovegood",
        role: "Editor, The Quibbler",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false, 
    },
    {
        name: "Remus Lupin",
        role: "Professor, Defence Against the Dark Arts",
        house: "Gryffindor",
        patronus: "wolf",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Walden Macnair",
        role: "Executioner, Committee of Disposal of Dangerous Creatures",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Draco Malfoy",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Lucius Malfoy",
        role: "School Governer of Hogwarts",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Narcissa Malfoy",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Madam Malkin",
        role: "Shop Owner, Madam Malkin's Robes for All Occasions",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Olympe Maxime",
        role: "Headmistress, Beauxbatons Academy of Magic",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ernest Macmillan",
        role: "student",
        house: "Hufflepuff",
        patronus: "boar",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Minerva McGonagall",
        role: "Professor, Transfiguration",
        house: "Gryffindor",
        patronus: "cat",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Alastor Moody",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Theodore Nott",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Garrick Ollivander",
        role: "Wandmaker",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Pansy Parkinson",
        role: "student",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Padma Patil",
        role: "student",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Parvati Patil",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Peter Pettigrew",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true, 
    },
    {
        name: "Antioch Peverell",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Cadmus Peverell",
        role: "Owner of the resurrection stone",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ignotus Peverell",
        role: "Owner of the invisibility cloak",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Irma Pince",
        role: "Librarian, Hogwarts",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Sturgis Podmore",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Poppy Pomfrey",
        role: "Matron, Hogwarts Hospital Wing",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Harry Potter",
        role: "student",
        house: "Gryffindor",
        patronus: "stag",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "James Potter I",
        house: "Gryffindor",
        patronus: "stag",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Lily J. Potter",
        house: "Gryffindor",
        patronus: "doe",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ernest Prang",
        role: "Driver of the Knight Bus",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Quirinus Quirrell",
        role: "Professor, Defence Against the Dark Arts",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Helena Ravenclaw",
        role: "Ravenclaw House Ghost",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Rowena Ravenclaw",
        role: "Founder, Hogwarts",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Mary Riddle",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Thomas Riddle",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Tom Riddle Sr",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Tom Riddle",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Demelza Robins",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Augustus Rockwood",
        role: "Unspeakable",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,  
    },
    {
        name: "Albert Runcorn",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Scabior",
        role: "Snatcher",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Newton Scamander ",
        role: "Author, Fantastic Beasts and Where to Find Them",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Rufus Scrimgeour",
        role: "Head of Auror Office",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Kingsley Shacklebolt",
        role: "Auror",
        patronus: "lynx",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Stanley Shunpike",
        role: "Conductor of the Knight Bus",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Aurora Sinistra",
        role: "Professor, Astronomy",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Rita Skeeter",
        role: "Gossip Correspondant for the Daily Prophet",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Horace Slughorn",
        role: "Professor, Potions",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Salazar Slytherin",
        role: "Founder, Hogwarts",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Hepzibah Smith",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Zacharias Smith",
        role: "student",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Severus Snape",
        role: "Professor, Potions",
        house: "Slytherin",
        patronus: "doe",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: true,
    },
    {
        name: "Alicia Spinnet",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Pomona Sprout",
        role: "Professor, Herbology",
        house: "Hufflepuff",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Pius Thicknesse",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Dean Thomas",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Andromeda Tonks",
        house: "Slytherin",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Nymphadora Tonks",
        role: "Auror",
        house: "Hufflepuff",
        patronus: "wolf",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Edward Tonks",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Travers",
        role: "Ministry of Magic Official",
        ministryOfMagic: true,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: true,  
    },
    {
        name: "Sybill Trelawney",
        role: "Professor, Divination",
        house: "Ravenclaw",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Dolores Umbridge",
        role: "Head of the Muggle Born Registration Commission",
        house: "Slytherin",
        patronus: "persian cat",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Emmeline Vance",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Romilda Vane",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: true,
        deathEater: false,  
    },
    {
        name: "Septima Vector",
        role: "Professor, Arithmancy",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    },
    {
        name: "Arthur Weasley",
        role: "Head, Misuse of Muggle Artifacts ",
        house: "Gryffindor",
        patronus: "weasel",
        ministryOfMagic: true,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "William Weasley",
        role: "Curse Breaker, Gringotts Bank",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Charles Weasley",
        role: "Dragonologist",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Fred Weasley",
        role: "co-owner of Weasleys' Wizard Wheezes",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "George Weasley",
        role: "co-owner of Weasleys' Wizard Wheezes",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ginevra Weasley",
        role: "student",
        house: "Gryffindor",
        patronus: "horse",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Molly Weasley",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Percy Weasley",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,
    },
    {
        name: "Ronald Weasley",
        role: "student",
        house: "Gryffindor",
        patronus: "jack russell terrier",
        ministryOfMagic: false,
        orderOfThePhoenix: true,
        dumbledoresArmy: true,
        deathEater: false,
    },
    {
        name: "Oliver Wood",
        role: "student",
        house: "Gryffindor",
        ministryOfMagic: false,
        orderOfThePhoenix: false,
        dumbledoresArmy: false,
        deathEater: false,  
    }
]